version: '3.8'

services:
  backend:
    build:
      context: ./BE
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - app-network
    dns:
      - 8.8.8.8
      - 8.8.4.4
    container_name: ip-lookup-backend

  frontend:
    build:
      context: ./FE
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network
    container_name: ips-app


networks:
  app-network:
    driver: bridge